# Start of script
# Automation
contents := $(shell main.sh foo)
define daily {
  break
}
define weekly {
  break
}
define monthly {
  break
}
define seasonally {
  break
}
define yearly {
  break
}
define flags {
  break
}
define fileStructure {
  break
}
define htmlStructure {
  break
}
define get {
  break
}
define fotw {
  break
}
export := $(shell main.sh foo)
# This file is highly incomplete and not functional. It is currently only a demo template. I am still learning how to write in GNU make

# File info
# File type: GNU make file (makefile)
# File version: 1 (Sunday, June 27th 2021 at 6:55 pm)
# Line count (including blank  lines and compiler line): 43

# End of script
